apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notebook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
      - name: notebook
        image: jtyberg/notebook
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notebook
  name: notebook
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: notebook
